[package]
name = "mlir-ffi-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
mlir-capi = { git = "https://github.com/lijinpei/mlir-capi-rs.git" }
llvm-capi = { git = "https://github.com/lijinpei/llvm-capi-rs.git" }
libc = "0.2"
libm = "0.2.11"

[[bin]]
name = "ir"
path = "src/bin/ir.rs"

[[bin]]
name = "pass"
path = "src/bin/pass.rs"

[[bin]]
name = "rewrite"
path = "src/bin/rewrite.rs"

[[bin]]
name = "llvm"
path = "src/bin/llvm.rs"

[[bin]]
name = "pdl"
path = "src/bin/pdl.rs"

[[bin]]
name = "quant"
path = "src/bin/quant.rs"

[[bin]]
name = "execution_engine"
path = "src/bin/execution_engine.rs"

[[bin]]
name = "sparse_tensor"
path = "src/bin/sparse_tensor.rs"

[[bin]]
name = "transform"
path = "src/bin/transform.rs"

[[bin]]
name = "transform_interpreter"
path = "src/bin/transform_interpreter.rs"

[[bin]]
name = "translation"
path = "src/bin/translation.rs"

[[bin]]
name = "irdl"
path = "src/bin/irdl.rs"
